services:
  nginx:
    container_name: nginx
    image: nginx
    build: 
      context: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    expose:
      - 9000
    volumes:
      - volume_wordpress:/var/www/html
    restart: always
    networks:
      - my_net
  mariadb:
    container_name: mariadb
    image: mariadb
    build: 
      context: ./requirements/mariadb
    env_file: .env
    expose:
      - 3306
    volumes:
      - volume_mariadb:/var/lib/mysql
    restart: always
    networks:
      - my_net
  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
    env_file: .env
    depends_on:
      - mariadb
    expose:
      - 9000
      - 3306
    volumes:
      - volume_wordpress:/var/www/html
    restart: always
    networks:
      - my_net

networks:
  my_net:
    name: my_net

volumes:
  volume_wordpress:
    driver: local
    driver_opts:
      type: none
      device: '/home/digarcia/data/wordpress'
      o: bind

  volume_mariadb:
    driver: local
    driver_opts:
      type: none
      device: '/home/digarcia/data/mariadb'
      o: bind
